### ISSUE TITLE
First Submission

### ISSUE THREAD

**Issue by dbampalikis** [NBISweden/EGA-SE-user-docs#6]
Short Summary: Use API to get rid of extra files in the submission.

In the first submission to the Central EGA, the data owner chose to only submit 10 files to test the system, though the metadata he uploaded contained information about all files this caused the submission to fail. It looks like it is possible to use the API to remove the extra entries.

Login URL for the API in the test system:
https://test.ega-archive.org/submission-api/v1/login

Here is documentation on deleting objects:
https://ega-archive.org/submission/programmatic_submissions/submitting-metadata#deletingObjects

And here is for logging in and so on:
https://ega-archive.org/submission/programmatic_submissions/how-to-use-the-api

(the full documentation is available on ega-archive.org and then menu Submission -> Tools -> Rest API)

Tasks:
- [x] Create a list of requests to delete objects
- [x] Email Adam with information
- [x] If requested, create a script for the deleting objects in the first submission

**Comment by mihai-sysbio** [comment]
This doesn't need a PR and it is completed.
